apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: 303713699681.dkr.ecr.us-east-1.amazonaws.com/eks-commerce-payment:28c45b433c74
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3004"