apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::303713699681:role/default-eks-node-group-20260509032806571000000009
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::303713699681:role/ECS-deployment-role
      username: github-actions
      groups:
      - system:masters