apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::303713699681:role/default-eks-node-group-20260509032806571000000009
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::303713699681:role/ECS-deployment-role
      username: github-actions
      groups:
      - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::303713699681:role/default-eks-node-group-20260509032806571000000009\n  groups:\n  - system:bootstrappers\n  - system:nodes\n  username: system:node:{{EC2PrivateDNSName}}\n\n- rolearn: arn:aws:iam::303713699681:role/ECS-deployment-role\n  username: github-actions\n  groups:\n  - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2026-05-09T03:38:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "77965"
  uid: 14e0a649-6b64-45d9-8119-7deec10e6999
