apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart       
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart     
  template:
    metadata:
      labels:
        app: cart   
    spec:
      containers:
        - name: cart   
          image: 303713699681.dkr.ecr.us-east-1.amazonaws.com/eks-commerce-cart:c571b1184ed6
          ports:
            - containerPort: 3000