apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: 303713699681.dkr.ecr.us-east-1.amazonaws.com/eks-commerce-cart:f6bf1968067b
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_URL
              value: "redis://redis.ecommerce.svc.cluster.local:6379"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog.ecommerce.svc.cluster.local"
              