apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
<<<<<<< HEAD
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: 303713699681.dkr.ecr.us-east-1.amazonaws.com/eks-commerce-notification:c3bc929b581d
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres.ecommerce.svc.cluster.local:5432/commerce"
            - name: DB_SCHEMA
              value: "notification"
=======
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/store(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
>>>>>>> 8cfff97 (ingress updated)
