apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/eks-commerce-notification:latest
          ports:
            - containerPort: 3000