apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  DB_HOST: "postgres.ecommerce.svc.cluster.local"
  DB_NAME: "commerce"
  DB_PORT: "5432"
  REDIS_HOST: "redis.ecommerce.svc.cluster.local"
  REDIS_PORT: "6379"