apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/eks-commerce-gateway:latest
          ports:
            - containerPort: 3000