apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 303713699681.dkr.ecr.us-east-1.amazonaws.com/eks-commerce-gateway:9e45939571c7
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog.ecommerce.svc.cluster.local"
            - name: CART_SERVICE_URL
              value: "http://cart.ecommerce.svc.cluster.local"
            - name: ORDER_SERVICE_URL
              value: "http://order.ecommerce.svc.cluster.local"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification.ecommerce.svc.cluster.local"