apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: 303713699681.dkr.ecr.us-east-1.amazonaws.com/eks-commerce-catalog:b29f2d6ad5b1
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres.ecommerce.svc.cluster.local:5432/commerce"
            - name: DB_SCHEMA
              value: "catalog"